# Generated by Django 5.0.6 on 2024-06-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='zip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
