# Generated by Django 5.0.6 on 2024-06-21 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanapp', '0002_booking_city_booking_state_booking_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Item in US Warehouse', 'Item in US Warehouse'), ('Item in Transit to Kenya', 'Item in Transit to Kenya'), ('Item in Kenyan Warehouse', 'Item in Kenyan Warehouse'), ('Item Sent for Delivery (Kenya)', 'Item Sent for Delivery (Kenya)')], default='Item in US Warehouse', max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
