# Generated by Django 5.0.6 on 2024-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanapp', '0004_package_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Item Picked', 'Item Picked'), ('Item in US Warehouse', 'Item in US Warehouse'), ('Item in Transit to Kenya', 'Item in Transit to Kenya'), ('Item in Kenyan Warehouse', 'Item in Kenyan Warehouse'), ('Item Sent for Delivery (Kenya)', 'Item Sent for Delivery (Kenya)')], default='Item in US Warehouse', max_length=100),
        ),
    ]
