# Generated by Django 5.0.6 on 2024-06-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanapp', '0005_alter_package_invoice_number_alter_package_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Item Picked', 'Item Picked'), ('Item in US Warehouse', 'Item in US Warehouse'), ('Item in Transit to Kenya', 'Item in Transit to Kenya'), ('Item in Kenyan Warehouse', 'Item in Kenyan Warehouse'), ('Item Dispatched for Delivery (Kenya)', 'Item Dispatched for Delivery (Kenya)')], default='Item in US Warehouse', max_length=100),
        ),
    ]
